species:
  - code: candida_albicans
    name: Candida albicans
    genome_dir: data/genomes/candida_albicans/
    gaf: data/gene_association.cgd
    cug_clade: true
  - code: candida_glabrata
    name: Candida glabrata
    genome_dir: data/genomes/candida_glabrata/
    gaf: data/gene_association.cgd
    cug_clade: false
go_obo: data/go.obo
adaptive:
  start_pct: 95
  step_pct: 5
  rounds: 7
wobble_only: true
wobble_aas:
  - Leu
  - Lys
  - Gln
  - Glu
  - Phe
  - Trp
  - Ser  # Important for CUG-clade species
output_dir: results